from __future__ import annotations

import argparse
import json
from pathlib import Path

from .manifest import PlannerConfig, UpstreamConfig, build_manifest, save_manifest
from .media import probe_video
from .planning import plan_chunks
from .runner import run_manifest
from .upstream import resolve_infer_script, resolve_weights_dir


def _default_work_dir(input_path: Path, scale: float) -> Path:
    return (Path.cwd() / "runs" / f"{input_path.stem}_x{scale:g}").resolve()


def _default_manifest_path(work_dir: Path) -> Path:
    return (work_dir / "manifest.json").resolve()


def _planner_from_args(args) -> PlannerConfig:
    return PlannerConfig(
        max_render_frames=args.max_render_frames,
        tiny_tail_threshold=args.tiny_tail_threshold,
        tail_merge_min_render_frames=args.tail_merge_min_render_frames,
    )


def cmd_plan(args) -> int:
    input_path = Path(args.input).expanduser().resolve()
    output_path = Path(args.output).expanduser().resolve()
    work_dir = Path(args.work_dir).expanduser().resolve() if args.work_dir else _default_work_dir(input_path, args.scale)
    manifest_path = Path(args.manifest).expanduser().resolve() if args.manifest else _default_manifest_path(work_dir)

    video = probe_video(input_path)
    planner = _planner_from_args(args)
    chunks = plan_chunks(
        video.total_frames,
        max_render_frames=planner.max_render_frames,
        tiny_tail_threshold=planner.tiny_tail_threshold,
        tail_merge_min_render_frames=planner.tail_merge_min_render_frames,
    )

    infer_script = None
    weights_dir = None
    if args.infer_script or args.upstream_root:
        infer_script = resolve_infer_script(args.upstream_root, args.infer_script)
        weights_dir = resolve_weights_dir(infer_script, args.weights_dir)

    manifest = build_manifest(
        input_path=input_path,
        output_path=output_path,
        work_dir=work_dir,
        scale=args.scale,
        video=video,
        planner=planner,
        chunks=chunks,
        upstream=UpstreamConfig(
            infer_script=str(infer_script) if infer_script else None,
            weights_dir=str(weights_dir) if weights_dir else None,
        ),
    )
    save_manifest(manifest, manifest_path)
    print(json.dumps(manifest.to_dict(), ensure_ascii=False, indent=2))
    return 0


def cmd_run(args) -> int:
    run_manifest(
        args.manifest,
        upstream_root=args.upstream_root,
        infer_script=args.infer_script,
        weights_dir=args.weights_dir,
        resume=args.resume,
    )
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Safe long-video runner around upstream FlashVSR")
    subparsers = parser.add_subparsers(dest="command", required=True)

    plan = subparsers.add_parser("plan", help="Inspect input video and generate a chunk manifest")
    plan.add_argument("--input", required=True, help="Input video path")
    plan.add_argument("--output", required=True, help="Final output video path")
    plan.add_argument("--scale", type=float, default=2.0, help="Upscale factor passed to upstream FlashVSR")
    plan.add_argument("--work-dir", help="Working directory for chunk outputs and manifest")
    plan.add_argument("--manifest", help="Manifest output path (default: <work-dir>/manifest.json)")
    plan.add_argument("--max-render-frames", type=int, default=21, help="Maximum upstream-friendly render window (5, 13, 21, ...)")
    plan.add_argument("--tiny-tail-threshold", type=int, default=8, help="Tail source length that triggers larger tail render windows")
    plan.add_argument(
        "--tail-merge-min-render-frames",
        type=int,
        default=13,
        help="When tail merging is triggered, use at least this render window length",
    )
    plan.add_argument("--upstream-root", help="Path to an upstream FlashVSR checkout")
    plan.add_argument("--infer-script", help="Path to upstream infer_flashvsr_v1.1_tiny_long_video.py")
    plan.add_argument("--weights-dir", help="Path to upstream FlashVSR-v1.1 weights directory")
    plan.set_defaults(func=cmd_plan)

    run = subparsers.add_parser("run", help="Render chunks from a manifest and concatenate them")
    run.add_argument("--manifest", required=True, help="Manifest JSON generated by `plan`")
    run.add_argument("--resume", action="store_true", help="Skip chunk outputs that already exist")
    run.add_argument("--upstream-root", help="Path to an upstream FlashVSR checkout")
    run.add_argument("--infer-script", help="Path to upstream infer_flashvsr_v1.1_tiny_long_video.py")
    run.add_argument("--weights-dir", help="Path to upstream FlashVSR-v1.1 weights directory")
    run.set_defaults(func=cmd_run)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
