from __future__ import annotations

import argparse
import json
from pathlib import Path

from .manifest import PlannerConfig
from .runner import run_manifest
from .service import ServiceConfig, serve
from .workflow import default_manifest_path, plan_video_job


def _default_work_dir(input_path: Path, scale: float) -> Path:
    return (Path.cwd() / "runs" / f"{input_path.stem}_x{scale:g}").resolve()


def _planner_from_args(args) -> PlannerConfig:
    return PlannerConfig(
        max_render_frames=args.max_render_frames,
        tiny_tail_threshold=args.tiny_tail_threshold,
        tail_merge_min_render_frames=args.tail_merge_min_render_frames,
    )


def cmd_plan(args) -> int:
    input_path = Path(args.input).expanduser().resolve()
    output_path = Path(args.output).expanduser().resolve()
    work_dir = Path(args.work_dir).expanduser().resolve() if args.work_dir else _default_work_dir(input_path, args.scale)
    manifest_path = Path(args.manifest).expanduser().resolve() if args.manifest else default_manifest_path(work_dir)

    manifest = plan_video_job(
        input_path=input_path,
        output_path=output_path,
        work_dir=work_dir,
        scale=args.scale,
        planner=_planner_from_args(args),
        manifest_path=manifest_path,
        upstream_root=args.upstream_root,
        infer_script=args.infer_script,
        weights_dir=args.weights_dir,
    )
    print(json.dumps(manifest.to_dict(), ensure_ascii=False, indent=2))
    return 0


def cmd_run(args) -> int:
    run_manifest(
        args.manifest,
        upstream_root=args.upstream_root,
        infer_script=args.infer_script,
        weights_dir=args.weights_dir,
        resume=args.resume,
    )
    return 0


def cmd_serve(args) -> int:
    if not args.upstream_root and not args.infer_script:
        raise SystemExit("serve requires --upstream-root or --infer-script")
    serve(
        ServiceConfig(
            host=args.host,
            port=args.port,
            state_dir=args.state_dir,
            scale=args.scale,
            max_queued_jobs=args.max_queued_jobs,
            planner=_planner_from_args(args),
            upstream_root=args.upstream_root,
            infer_script=args.infer_script,
            weights_dir=args.weights_dir,
        )
    )
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Safe long-video runner around upstream FlashVSR")
    subparsers = parser.add_subparsers(dest="command", required=True)

    plan = subparsers.add_parser("plan", help="Inspect input video and generate a chunk manifest")
    plan.add_argument("--input", required=True, help="Input video path")
    plan.add_argument("--output", required=True, help="Final output video path")
    plan.add_argument("--scale", type=float, default=2.0, help="Upscale factor passed to upstream FlashVSR")
    plan.add_argument("--work-dir", help="Working directory for chunk outputs and manifest")
    plan.add_argument("--manifest", help="Manifest output path (default: <work-dir>/manifest.json)")
    plan.add_argument(
        "--max-render-frames",
        type=int,
        default=21,
        help="Maximum long-pipeline render window (21, 29, 37, ...)",
    )
    plan.add_argument("--tiny-tail-threshold", type=int, default=8, help="Tail source length that triggers larger tail render windows")
    plan.add_argument(
        "--tail-merge-min-render-frames",
        type=int,
        default=21,
        help="When tail merging is triggered, use at least this render window length",
    )
    plan.add_argument("--upstream-root", help="Path to an upstream FlashVSR checkout")
    plan.add_argument("--infer-script", help="Path to upstream infer_flashvsr_v1.1_tiny_long_video.py")
    plan.add_argument("--weights-dir", help="Path to upstream FlashVSR-v1.1 weights directory")
    plan.set_defaults(func=cmd_plan)

    run = subparsers.add_parser("run", help="Render chunks from a manifest and concatenate them")
    run.add_argument("--manifest", required=True, help="Manifest JSON generated by `plan`")
    run.add_argument("--resume", action="store_true", help="Skip chunk outputs that already exist")
    run.add_argument("--upstream-root", help="Path to an upstream FlashVSR checkout")
    run.add_argument("--infer-script", help="Path to upstream infer_flashvsr_v1.1_tiny_long_video.py")
    run.add_argument("--weights-dir", help="Path to upstream FlashVSR-v1.1 weights directory")
    run.set_defaults(func=cmd_run)

    serve_parser = subparsers.add_parser("serve", help="Run an async HTTP service for queued FlashVSR jobs")
    serve_parser.add_argument("--host", default="0.0.0.0", help="Bind host for the HTTP service")
    serve_parser.add_argument("--port", type=int, default=8000, help="Bind port for the HTTP service")
    serve_parser.add_argument("--state-dir", default="service_state", help="Directory for uploaded videos and job state")
    serve_parser.add_argument("--scale", type=float, default=2.0, help="Upscale factor applied to submitted videos")
    serve_parser.add_argument(
        "--max-queued-jobs",
        type=int,
        default=0,
        help="Maximum number of queued jobs waiting behind the active worker (0 means unlimited)",
    )
    serve_parser.add_argument(
        "--max-render-frames",
        type=int,
        default=21,
        help="Maximum long-pipeline render window (21, 29, 37, ...)",
    )
    serve_parser.add_argument(
        "--tiny-tail-threshold",
        type=int,
        default=8,
        help="Tail source length that triggers larger tail render windows",
    )
    serve_parser.add_argument(
        "--tail-merge-min-render-frames",
        type=int,
        default=21,
        help="When tail merging is triggered, use at least this render window length",
    )
    serve_parser.add_argument("--upstream-root", help="Path to an upstream FlashVSR checkout")
    serve_parser.add_argument("--infer-script", help="Path to upstream infer_flashvsr_v1.1_tiny_long_video.py")
    serve_parser.add_argument("--weights-dir", help="Path to upstream FlashVSR-v1.1 weights directory")
    serve_parser.set_defaults(func=cmd_serve)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
